package com.pactera.stash.mapper;

import com.pactera.stash.model.Record;
import com.pactera.stash.model.RecordExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RecordMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.record
	 * @mbg.generated  Sun Nov 13 19:41:46 CST 2016
	 */
	long countByExample(RecordExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.record
	 * @mbg.generated  Sun Nov 13 19:41:46 CST 2016
	 */
	int deleteByExample(RecordExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.record
	 * @mbg.generated  Sun Nov 13 19:41:46 CST 2016
	 */
	int insert(Record record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.record
	 * @mbg.generated  Sun Nov 13 19:41:46 CST 2016
	 */
	int insertSelective(Record record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.record
	 * @mbg.generated  Sun Nov 13 19:41:46 CST 2016
	 */
	List<Record> selectByExample(RecordExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.record
	 * @mbg.generated  Sun Nov 13 19:41:46 CST 2016
	 */
	int updateByExampleSelective(@Param("record") Record record, @Param("example") RecordExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.record
	 * @mbg.generated  Sun Nov 13 19:41:46 CST 2016
	 */
	int updateByExample(@Param("record") Record record, @Param("example") RecordExample example);
}