package com.pactera.stash.mapper;

import com.pactera.stash.model.Stock;
import com.pactera.stash.model.StockExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface StockMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.stock
	 * @mbg.generated  Sun Nov 13 19:41:46 CST 2016
	 */
	long countByExample(StockExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.stock
	 * @mbg.generated  Sun Nov 13 19:41:46 CST 2016
	 */
	int deleteByExample(StockExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.stock
	 * @mbg.generated  Sun Nov 13 19:41:46 CST 2016
	 */
	int deleteByPrimaryKey(String code);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.stock
	 * @mbg.generated  Sun Nov 13 19:41:46 CST 2016
	 */
	int insert(Stock record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.stock
	 * @mbg.generated  Sun Nov 13 19:41:46 CST 2016
	 */
	int insertSelective(Stock record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.stock
	 * @mbg.generated  Sun Nov 13 19:41:46 CST 2016
	 */
	List<Stock> selectByExample(StockExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.stock
	 * @mbg.generated  Sun Nov 13 19:41:46 CST 2016
	 */
	Stock selectByPrimaryKey(String code);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.stock
	 * @mbg.generated  Sun Nov 13 19:41:46 CST 2016
	 */
	int updateByExampleSelective(@Param("record") Stock record, @Param("example") StockExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.stock
	 * @mbg.generated  Sun Nov 13 19:41:46 CST 2016
	 */
	int updateByExample(@Param("record") Stock record, @Param("example") StockExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.stock
	 * @mbg.generated  Sun Nov 13 19:41:46 CST 2016
	 */
	int updateByPrimaryKeySelective(Stock record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.stock
	 * @mbg.generated  Sun Nov 13 19:41:46 CST 2016
	 */
	int updateByPrimaryKey(Stock record);
}