package com.pactera.stash.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class RecordExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table public.record
	 * @mbg.generated  Sun Nov 13 19:41:46 CST 2016
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table public.record
	 * @mbg.generated  Sun Nov 13 19:41:46 CST 2016
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table public.record
	 * @mbg.generated  Sun Nov 13 19:41:46 CST 2016
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.record
	 * @mbg.generated  Sun Nov 13 19:41:46 CST 2016
	 */
	public RecordExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.record
	 * @mbg.generated  Sun Nov 13 19:41:46 CST 2016
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.record
	 * @mbg.generated  Sun Nov 13 19:41:46 CST 2016
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.record
	 * @mbg.generated  Sun Nov 13 19:41:46 CST 2016
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.record
	 * @mbg.generated  Sun Nov 13 19:41:46 CST 2016
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.record
	 * @mbg.generated  Sun Nov 13 19:41:46 CST 2016
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.record
	 * @mbg.generated  Sun Nov 13 19:41:46 CST 2016
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.record
	 * @mbg.generated  Sun Nov 13 19:41:46 CST 2016
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.record
	 * @mbg.generated  Sun Nov 13 19:41:46 CST 2016
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.record
	 * @mbg.generated  Sun Nov 13 19:41:46 CST 2016
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.record
	 * @mbg.generated  Sun Nov 13 19:41:46 CST 2016
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table public.record
	 * @mbg.generated  Sun Nov 13 19:41:46 CST 2016
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andTimeIsNull() {
			addCriterion("t_time is null");
			return (Criteria) this;
		}

		public Criteria andTimeIsNotNull() {
			addCriterion("t_time is not null");
			return (Criteria) this;
		}

		public Criteria andTimeEqualTo(Date value) {
			addCriterion("t_time =", value, "time");
			return (Criteria) this;
		}

		public Criteria andTimeNotEqualTo(Date value) {
			addCriterion("t_time <>", value, "time");
			return (Criteria) this;
		}

		public Criteria andTimeGreaterThan(Date value) {
			addCriterion("t_time >", value, "time");
			return (Criteria) this;
		}

		public Criteria andTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("t_time >=", value, "time");
			return (Criteria) this;
		}

		public Criteria andTimeLessThan(Date value) {
			addCriterion("t_time <", value, "time");
			return (Criteria) this;
		}

		public Criteria andTimeLessThanOrEqualTo(Date value) {
			addCriterion("t_time <=", value, "time");
			return (Criteria) this;
		}

		public Criteria andTimeIn(List<Date> values) {
			addCriterion("t_time in", values, "time");
			return (Criteria) this;
		}

		public Criteria andTimeNotIn(List<Date> values) {
			addCriterion("t_time not in", values, "time");
			return (Criteria) this;
		}

		public Criteria andTimeBetween(Date value1, Date value2) {
			addCriterion("t_time between", value1, value2, "time");
			return (Criteria) this;
		}

		public Criteria andTimeNotBetween(Date value1, Date value2) {
			addCriterion("t_time not between", value1, value2, "time");
			return (Criteria) this;
		}

		public Criteria andCodeIsNull() {
			addCriterion("c_code is null");
			return (Criteria) this;
		}

		public Criteria andCodeIsNotNull() {
			addCriterion("c_code is not null");
			return (Criteria) this;
		}

		public Criteria andCodeEqualTo(String value) {
			addCriterion("c_code =", value, "code");
			return (Criteria) this;
		}

		public Criteria andCodeNotEqualTo(String value) {
			addCriterion("c_code <>", value, "code");
			return (Criteria) this;
		}

		public Criteria andCodeGreaterThan(String value) {
			addCriterion("c_code >", value, "code");
			return (Criteria) this;
		}

		public Criteria andCodeGreaterThanOrEqualTo(String value) {
			addCriterion("c_code >=", value, "code");
			return (Criteria) this;
		}

		public Criteria andCodeLessThan(String value) {
			addCriterion("c_code <", value, "code");
			return (Criteria) this;
		}

		public Criteria andCodeLessThanOrEqualTo(String value) {
			addCriterion("c_code <=", value, "code");
			return (Criteria) this;
		}

		public Criteria andCodeLike(String value) {
			addCriterion("c_code like", value, "code");
			return (Criteria) this;
		}

		public Criteria andCodeNotLike(String value) {
			addCriterion("c_code not like", value, "code");
			return (Criteria) this;
		}

		public Criteria andCodeIn(List<String> values) {
			addCriterion("c_code in", values, "code");
			return (Criteria) this;
		}

		public Criteria andCodeNotIn(List<String> values) {
			addCriterion("c_code not in", values, "code");
			return (Criteria) this;
		}

		public Criteria andCodeBetween(String value1, String value2) {
			addCriterion("c_code between", value1, value2, "code");
			return (Criteria) this;
		}

		public Criteria andCodeNotBetween(String value1, String value2) {
			addCriterion("c_code not between", value1, value2, "code");
			return (Criteria) this;
		}

		public Criteria andIndexIsNull() {
			addCriterion("d_index is null");
			return (Criteria) this;
		}

		public Criteria andIndexIsNotNull() {
			addCriterion("d_index is not null");
			return (Criteria) this;
		}

		public Criteria andIndexEqualTo(Double value) {
			addCriterion("d_index =", value, "index");
			return (Criteria) this;
		}

		public Criteria andIndexNotEqualTo(Double value) {
			addCriterion("d_index <>", value, "index");
			return (Criteria) this;
		}

		public Criteria andIndexGreaterThan(Double value) {
			addCriterion("d_index >", value, "index");
			return (Criteria) this;
		}

		public Criteria andIndexGreaterThanOrEqualTo(Double value) {
			addCriterion("d_index >=", value, "index");
			return (Criteria) this;
		}

		public Criteria andIndexLessThan(Double value) {
			addCriterion("d_index <", value, "index");
			return (Criteria) this;
		}

		public Criteria andIndexLessThanOrEqualTo(Double value) {
			addCriterion("d_index <=", value, "index");
			return (Criteria) this;
		}

		public Criteria andIndexIn(List<Double> values) {
			addCriterion("d_index in", values, "index");
			return (Criteria) this;
		}

		public Criteria andIndexNotIn(List<Double> values) {
			addCriterion("d_index not in", values, "index");
			return (Criteria) this;
		}

		public Criteria andIndexBetween(Double value1, Double value2) {
			addCriterion("d_index between", value1, value2, "index");
			return (Criteria) this;
		}

		public Criteria andIndexNotBetween(Double value1, Double value2) {
			addCriterion("d_index not between", value1, value2, "index");
			return (Criteria) this;
		}

		public Criteria andDColIsNull() {
			addCriterion("d_col is null");
			return (Criteria) this;
		}

		public Criteria andDColIsNotNull() {
			addCriterion("d_col is not null");
			return (Criteria) this;
		}

		public Criteria andDColEqualTo(Double value) {
			addCriterion("d_col =", value, "dCol");
			return (Criteria) this;
		}

		public Criteria andDColNotEqualTo(Double value) {
			addCriterion("d_col <>", value, "dCol");
			return (Criteria) this;
		}

		public Criteria andDColGreaterThan(Double value) {
			addCriterion("d_col >", value, "dCol");
			return (Criteria) this;
		}

		public Criteria andDColGreaterThanOrEqualTo(Double value) {
			addCriterion("d_col >=", value, "dCol");
			return (Criteria) this;
		}

		public Criteria andDColLessThan(Double value) {
			addCriterion("d_col <", value, "dCol");
			return (Criteria) this;
		}

		public Criteria andDColLessThanOrEqualTo(Double value) {
			addCriterion("d_col <=", value, "dCol");
			return (Criteria) this;
		}

		public Criteria andDColIn(List<Double> values) {
			addCriterion("d_col in", values, "dCol");
			return (Criteria) this;
		}

		public Criteria andDColNotIn(List<Double> values) {
			addCriterion("d_col not in", values, "dCol");
			return (Criteria) this;
		}

		public Criteria andDColBetween(Double value1, Double value2) {
			addCriterion("d_col between", value1, value2, "dCol");
			return (Criteria) this;
		}

		public Criteria andDColNotBetween(Double value1, Double value2) {
			addCriterion("d_col not between", value1, value2, "dCol");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table public.record
	 * @mbg.generated  Sun Nov 13 19:41:46 CST 2016
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table public.record
     *
     * @mbg.generated do_not_delete_during_merge Sun Nov 13 00:52:51 CST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}