package com.pactera.stash.model;

import java.util.Date;

public class Record {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.record.t_time
	 * @mbg.generated  Sun Nov 13 19:41:46 CST 2016
	 */
	private Date time;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.record.c_code
	 * @mbg.generated  Sun Nov 13 19:41:46 CST 2016
	 */
	private String code;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.record.d_index
	 * @mbg.generated  Sun Nov 13 19:41:46 CST 2016
	 */
	private Double index;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.record.d_col
	 * @mbg.generated  Sun Nov 13 19:41:46 CST 2016
	 */
	private Double dCol;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.record.t_time
	 * @return  the value of public.record.t_time
	 * @mbg.generated  Sun Nov 13 19:41:46 CST 2016
	 */
	public Date getTime() {
		return time;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.record.t_time
	 * @param time  the value for public.record.t_time
	 * @mbg.generated  Sun Nov 13 19:41:46 CST 2016
	 */
	public void setTime(Date time) {
		this.time = time;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.record.c_code
	 * @return  the value of public.record.c_code
	 * @mbg.generated  Sun Nov 13 19:41:46 CST 2016
	 */
	public String getCode() {
		return code;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.record.c_code
	 * @param code  the value for public.record.c_code
	 * @mbg.generated  Sun Nov 13 19:41:46 CST 2016
	 */
	public void setCode(String code) {
		this.code = code;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.record.d_index
	 * @return  the value of public.record.d_index
	 * @mbg.generated  Sun Nov 13 19:41:46 CST 2016
	 */
	public Double getIndex() {
		return index;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.record.d_index
	 * @param index  the value for public.record.d_index
	 * @mbg.generated  Sun Nov 13 19:41:46 CST 2016
	 */
	public void setIndex(Double index) {
		this.index = index;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.record.d_col
	 * @return  the value of public.record.d_col
	 * @mbg.generated  Sun Nov 13 19:41:46 CST 2016
	 */
	public Double getdCol() {
		return dCol;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.record.d_col
	 * @param dCol  the value for public.record.d_col
	 * @mbg.generated  Sun Nov 13 19:41:46 CST 2016
	 */
	public void setdCol(Double dCol) {
		this.dCol = dCol;
	}
}