package com.pactera.stash.model;

public class Stock {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.stock.c_code
	 * @mbg.generated  Sun Nov 13 19:41:46 CST 2016
	 */
	private String code;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.stock.c_name
	 * @mbg.generated  Sun Nov 13 19:41:46 CST 2016
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.stock.c_org
	 * @mbg.generated  Sun Nov 13 19:41:46 CST 2016
	 */
	private String org;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.stock.c_code
	 * @return  the value of public.stock.c_code
	 * @mbg.generated  Sun Nov 13 19:41:46 CST 2016
	 */
	public String getCode() {
		return code;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.stock.c_code
	 * @param code  the value for public.stock.c_code
	 * @mbg.generated  Sun Nov 13 19:41:46 CST 2016
	 */
	public void setCode(String code) {
		this.code = code;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.stock.c_name
	 * @return  the value of public.stock.c_name
	 * @mbg.generated  Sun Nov 13 19:41:46 CST 2016
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.stock.c_name
	 * @param name  the value for public.stock.c_name
	 * @mbg.generated  Sun Nov 13 19:41:46 CST 2016
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.stock.c_org
	 * @return  the value of public.stock.c_org
	 * @mbg.generated  Sun Nov 13 19:41:46 CST 2016
	 */
	public String getOrg() {
		return org;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.stock.c_org
	 * @param org  the value for public.stock.c_org
	 * @mbg.generated  Sun Nov 13 19:41:46 CST 2016
	 */
	public void setOrg(String org) {
		this.org = org;
	}
}